# Locally, backups go to SeaweedFS (component object-storage).
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ObjectStore
      name: backups
    patch: |
      - op: add
        path: /spec/configuration/endpointURL
        value: http://seaweedfs.object-storage.svc:8333
